### ISSUE TITLE
pgweb - golang postgresql web interface

### ISSUE THREAD

**Issue by tehbilly** [microbox/microbox.github.io#4]
Should be easier than gogs, and the "official" image is entirely too large (being based on the golang image). I think this would be a great candidate.

**Comment by microbox** [comment]
You are right! 

The latest version of pgweb 0.5.1 is available to use.

`docker run --rm -it -p 8080:8080 -e URL="postgres://user:password@host:port/database?sslmode=[mode]" microbox/pgweb`
