### ISSUE TITLE
rethinkdb 2.0.1

### ISSUE THREAD

**Issue by falkenlabs** [microbox/microbox.github.io#5]
Hi, 

I try to compile rethinkdb 2.0.1 with buildroot from [progrium/rootbuilder](https://github.com/progrium/rootbuilder) but without any success.

Could you please show me your Config.in or .mk files ? 

`Config.in`
```shell
config BR2_PACKAGE_RETHINKDB
  bool "rethinkdb"
```

`rethinkdb.mk`
```shell
RETHINKDB_VERSION = 2.0.1
RETHINKDB_SOURCE = rethinkdb-$(RETHINKDB_VERSION).tgz
RETHINKDB_SITE = http://download.rethinkdb.com/dist/
RETHINKDB_CONF_OPTS = --allow-fetch
```

**Comment by e2tox** [comment]
Hi Falkenlabs.

The cross compiler may cause some unexpected error. I don't use it. Instead of that I create the image from official release.

I have update to the latest version 2.0.4.

`
docker pull microbox/rethinkdb
`

-ling
